# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointer', '0005_auto_20170520_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 20, 22, 5, 47, 181572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2017, 5, 20, 22, 5, 47, 181572, tzinfo=utc)),
        ),
    ]
